name: Main

on:
  push:
    branches: [ main ]
  pull_request: {}

env:           #   1) одна переменная, чтобы не повторять
  JAVA_VERSION: "17"

jobs:

  # 1️⃣  Общие юнит‑тесты + JVM‑тесты ----------------------------
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3   # и кеш, и wrapper summary
                                               # :contentReference[oaicite:0]{index=0}

      - name: Run all unit tests (common + JVM)
        run: ./gradlew :shared:allTests --stacktrace

  # 2️⃣  Android‑сборка ------------------------------------------
  android-build:
    needs: tests                                 # запускаем только если тесты зелёные
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - uses: gradle/actions/setup-gradle@v3

      - name: Assemble Debug APK
        run: ./gradlew :androidApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: androidApp/build/outputs/apk/debug/*.apk
